# -*- coding: utf-8 -*-
"""amlexp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9bOS1sCroxeW-ZsY8DrOgx5XXCaWoTp
"""

!pip install xlrd

from google.colab import files

uploaded = files.upload()

import zipfile

zip_file = "Student grade Prediction.zip"

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall()

print("Files extracted successfully!")

import pandas as pd

df = pd.read_excel(
    "Student grade Prediction/cgpaPRED.xls",
    engine="xlrd"
)

df.head()

print(df.columns.tolist())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import pandas as pd

df = pd.read_excel("Student grade Prediction/cgpaPRED.xls")

df.head()