# -*- coding: utf-8 -*-
"""amlexp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-h9sDWc-f0EnW-gt0yThNgHaCxBCzNT
"""

import matplotlib.pyplot as plt
import numpy as np

# Input section
x = np.array(input("Enter x Values (Comma-separated): ").split(","), dtype=float)
y = np.array(input("Enter y values (Comma-separated): ").split(","), dtype=float)

n = len(x)
sumx = 0
sumy = 0
sumxy = 0
sumxx = 0

# Calculation loops for slope and intercept
for i in range(n):
    sumx += x[i]
    sumy += y[i]
    sumxy += x[i] * y[i]
    sumxx += x[i] * x[i]

m = ((n * sumxy) - (sumx * sumy)) / ((n * sumxx) - (sumx * sumx))
b = (sumy - m * sumx) / n

y_pred = []
for i in range(n):
    y_pred.append(m * x[i] + b)

# Error metrics initialization
mae = 0
mse = 0
for i in range(n):
    error = y[i] - y_pred[i]
    mae += abs(error)
    mse += error ** 2

mae = mae / n
mse = mse / n
rmse = mse ** 0.5

mean_y = sum(y) / n

# R2 Score calculation
ss_res = 0
ss_tot = 0
for i in range(n):
    ss_res += (y[i] - y_pred[i]) ** 2
    ss_tot += (y[i] - mean_y) ** 2

r2 = 1 - (ss_res / ss_tot)

# Printing Output
print(f"Linear Regression Equation: y={m:.4f}x + {b:.4f}")
print(f"Mean squared ERROR (MSE): {mse:.4f}")
print(f"mean Absolute ERROR (MAE): {mae:.4f}")
print(f"Root mean squared ERROR (RMSE): {rmse:.4f}")
print(f"R² score: {r2:.4f}")

# Plotting Linear Regression
plt.scatter(x, y, label="Data Points")
plt.plot(x, y_pred, color="red", label="Regression Line")
plt.title("Linear Regression")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.show()

# Plotting Model Metrics
metrics = ["MSE", "MAE", "RMSE", "R2"]
values = [mse, mae, rmse, r2]

plt.scatter(metrics, values)
for i in range(4):
    plt.text(metrics[i], values[i], round(values[i], 4))
plt.title("Model metrics")
plt.xlabel("Metrics")
plt.ylabel("value")
plt.grid(True)
plt.show()