# -*- coding: utf-8 -*-
"""AMLEXP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFIW6IsrUkKRSt9HF_NV6-IOERkVd7HC
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
print("1. Generating Sample Data...")
np.random.seed(42)
num_samples = 100
X1 = np.random.rand(num_samples, 1) * 10
X2 = np.random.rand(num_samples, 1) * 5
X3 = np.random.rand(num_samples, 1) * 20
y = 2 * X1 + 3 * X2 - 1 * X3 + 5 + np.random.randn(num_samples, 1) * 2
X = pd.DataFrame(np.hstack((X1, X2, X3)), columns=['Feature_1', 'Feature_2', 'Feature_3'])
y = pd.DataFrame(y, columns=['Target'])
print("Features (X) head:")
display(X.head())
print("\nTarget (y) head:")
display(y.head())

print("\n2. Splitting Data into Training and Testing Sets...")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")

print("\n3. Initializing and Training the Model...")
model = LinearRegression()
model.fit(X_train, y_train)
print("Model training complete.")
print(f"Coefficients: {model.coef_[0]}")
print(f"Intercept: {model.intercept_[0]}")

print("\n4. Making Predictions...")
y_pred = model.predict(X_test)
predictions_df = pd.DataFrame({'Actual': y_test.values.flatten(), 'Predicted': y_pred.flatten()})
print("Actual vs. Predicted values head:")
display(predictions_df.head())

print("\n5. Evaluating the Model...")
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

print("\n6. Visualizing Predictions...")
plt.figure(figsize=(10, 6))
sns.regplot(x=y_test.values.flatten(), y=y_pred.flatten(), scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
plt.xlabel("Actual Target Values")
plt.ylabel("Predicted Target Values")
plt.title("Actual vs. Predicted Target Values")
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

