# -*- coding: utf-8 -*-
"""amllabexp6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wtei3ymFRbBCvBuvYafPrrzrPB8zgSJ
"""

import pandas as pd
from scipy.stats import chi2_contingency

data = pd.DataFrame(
    {
        "Bias_Yes": [10, 5],
        "Bias_No":  [5, 10]
    },
    index=["Sports_Yes", "Sports_No"]
)

print("Contingency Table:")
print(data)

chi2, p_value, dof, expected = chi2_contingency(data, correction=False)

print("\nChi-square statistic:", chi2)
print("P-value:", p_value)
print("Degrees of freedom:", dof)

print("\nExpected frequencies:")
print(expected)

alpha = 0.05
chi_square_tabulated = 3.841

if chi2 > chi_square_tabulated:
    print("\nResult: Reject H0")
    print("Sports is significantly related to Bias.")
else:
    print("\nResult: Fail to reject H0")
    print("Sports is not significantly related to Bias.")

import pandas as pd
from scipy.stats import chi2_contingency

data = pd.DataFrame(
    {
        "Bias_Yes": [30,10],
        "Bias_No":  [20,40]
    },
    index=["Sports_Yes", "Sports_No"]
)

print("Contingency Table:")
print(data)

chi2, p_value, dof, expected = chi2_contingency(data, correction=False)

print("\nChi-square statistic:", chi2)
print("P-value:", p_value)
print("Degrees of freedom:", dof)

print("\nExpected frequencies:")
print(expected)

alpha = 0.05
chi_square_tabulated = 3.841

if chi2 > chi_square_tabulated:
    print("\nResult: Reject H0")
    print("Sports is significantly related to Bias.")
else:
    print("\nResult: Fail to reject H0")
    print("Sports is not significantly related to Bias.")