# -*- coding: utf-8 -*-
"""amllab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17dQC1Y_5Ys7GMdB6shRriuKG0xsHoBqM
"""

import numpy as np
rainfall = ['High', 'High', 'High', 'Low', 'Low', 'Low']
soiltype = ['Loamy', 'Sandy', 'Clay', 'Loamy', 'Sandy', 'Clay']
yield_value = ['Good', 'Good', 'Good', 'Poor', 'Poor', 'Good']

# Function to calculate OneR error
def calculate_error(feature, target):
    values = set(feature)
    errors = 0

    for value in values:
        # Get target values for this feature value
        targets = [
            target[i] for i in range(len(feature))
            if feature[i] == value
        ]

        # Find majority class
        majority = max(set(targets), key=targets.count)

        # Count errors
        errors += sum(1 for x in targets if x != majority)

    # Error percentage
    return (errors / len(target)) * 100


# Calculate errors
rainfall_error = calculate_error(rainfall, yield_value)
soil_error = calculate_error(soiltype, yield_value)

print("Rainfall Error =", rainfall_error, "%")
print("Soil Type Error =", soil_error, "%")