# -*- coding: utf-8 -*-
"""amllab08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwIYIIFQWnswu2MqQBsQ8H9QDcaolaIu
"""

import numpy as np
from scipy.stats import pearsonr

X1 = np.array([1, 2, 3, 7, 8, 9], dtype=float)
X2 = np.array([2, 3, 4, 6, 7, 8], dtype=float)
X3 = np.array([5, 4, 3, 3, 2, 1], dtype=float)
Y  = np.array([0, 0, 0, 1, 1, 1], dtype=float)

def pearson_correlation(X, Y):
    x_mean = np.mean(X)
    y_mean = np.mean(Y)

    numerator = np.sum((X - x_mean) * (Y - y_mean))

    denominator = np.sqrt(
        np.sum((X - x_mean) ** 2) *
        np.sum((Y - y_mean) ** 2)
    )

    return numerator / denominator

print("Correlation with Y:")

print("r(X1,Y) =", pearson_correlation(X1, Y))
print("r(X2,Y) =", pearson_correlation(X2, Y))
print("r(X3,Y) =", pearson_correlation(X3, Y))


print("\nFeature-Feature Correlations:")

print("r(X1,X2) =", pearson_correlation(X1, X2))
print("r(X2,X3) =", pearson_correlation(X2, X3))
print("r(X1,X3) =", pearson_correlation(X1, X3))


Y = np.array([0, 0, 0, 1, 1, 1])


def corr(x, y):
    return np.corrcoef(x, y)[0, 1]

def cfs_merit(subset):

    k = len(subset)

    r_cf = np.mean([
        abs(corr(X[f], Y))
        for f in subset
    ])

    pairs = list(combinations(subset, 2))

    if pairs:
        r_ff = np.mean([
            abs(corr(X[a], X[b]))
            for a, b in pairs
        ])
    else:
        r_ff = 0

    merit = (k * r_cf) / np.sqrt(
        k + k * (k - 1) * r_ff
    )

    return merit

for k in range(1, len(X) + 1):

    for subset in combinations(X.keys(), k):

        merit = cfs_merit(subset)

        print(
            subset,
            "CFS Merit =",
            round(merit, 4)
        )